REWRITING_INSTRUCTION_AUX_LINKING_PRIVACY_DBBIO = (
    "You are anonymising a document by coarsening. An adversary with auxiliary "
    "information about the person has provided feedback on which details in the "
    "current text still enable re-identification. Your task is to rewrite the "
    "document, by generalising the details the adversary flagged so "
    "they no longer narrow the population to this individual.\n\n"

    "Every detail the adversary identifies as distinctive must be transformed. "
    "Coarsen by generalising the detail to a broader true statement, or remove it "
    "entirely if any generalisation broad enough to be non-identifying would convey no useful information. "
    "Assume the adversary can hold any background knowledge that could reasonably be obtained about "
    "a person.\n\n"

    "Leave unflagged details at their original level of specificity to preserve utility. "
    "The one exception is the subject's name: always generalise or remove any name "
    "referring to the person the document is about, whether or not the adversary's "
    "feedback flagged it, since a name is a guaranteed and maximally identifying detail.\n\n"

    "Coarsening only removes information; it never invents or replaces it. Do "
    "not substitute a flagged value for a different specific value ('my husband "
    "and I' → 'my wife and I' is a fabrication, not a coarsening). Valid moves "
    "are generalisation ('my husband and I' → 'my partner and I').\n\n"

    "Consider conjunctions carefully: two individually innocuous details may "
    "jointly re-identify. If the adversary's feedback flags a combination "
    "rather than a single detail, coarsen enough of the combination to break "
    "the pattern.\n\n"

    "Preserve the original text's structure, ordering, and register. The output "
    "must read as an ordinary document. Do not signal that the document has "
    "been anonymised, and do not introduce placeholders, redaction markers, or "
    "generic phrasing such as \"an individual\" where a specific detail would "
    "be natural.\n\n"

    "{format_instructions}\n\n"

    "The current document is:\n{prev_rewriting}\n\n"
    "Thhe adversary feedback is:\n{reflection_privacy}"
)

DETECTION_INSTRUCTION = (
    "Let's first complete the personally identifiable information detection task, "
    "given the person description text, you need to answer the name of the"
    " person that is mainly talked about by the text, then identify every entities "
    "(including words, dates, and numerals) in the provided person description text that"
    " can be connected to the person being talked about, such that if these entities "
    "are removed the result text is anonymized, namely people can not know who is described in the text. \n"
    "{format_instructions_1}\nThe person description text is here:\n{input_text}")
GENERAL_SYSTEM_INSTRUCTION = ("You are an efficient assistant. "
                              "Only respond with the given JSON template filled with your answers.")
WHOLE_TASK_INSTRUCTION = ("You are a text anonymization annotator. I require your assistance in anonymizing the given "
                          "description text to facilitate sharing it "
                          "with other people while preserving its utility. \n"
                          "Let's think step by step, to achieve this goal, "
                          "first, you need to detect all the sensitive entities. "
                          "Second, you need to rewrite the text by replacing sensitive entities with more general "
                          "entities to make them less specific and insert or delete tokens necessary to ensure"
                          " the final output text is fluent and natural. The style and format of the output text "
                          "should be consistent with the input text.")
REFELECTION_PRIVACY_REWRITING_INSTRUCTION = (
    "Here is the list of the sensitive entities that still can be used to correctly infer"
    "the identity of the people being talked about by your anonymized text."
    " Please further generalize the sensitive entities in your anonymized text"
    " to give me a better anonymized text with a higher level of safety. "
    "Note that you are only allowed to decrease the specificity by replacing sensitive"
    " words or entities with more general one and should not delete the"
    " content of the text. Only tokens necessary to make the sentence natural and fluent can be added or deleted. "
    "Please follow the instructions precisely and try to change as little as possible, keeping "
    "the original text in tact as much as possible. "
    "\n{format_instructions_3}\nThe entity list is here:\n{reflection_privacy}"
)
SIMPLE_REWRITING_INSTRUCTION = (
    "You are an expert anonymizer that carefully choose some of the personally identifiable entities (including words, dates, and numerals) of the given biography text "
    "that can be used to connect the person being talked about"
    " and then generalize them to make the biography text anonymous, namely the biography text can be suitable"
    " to describe not only a specific one person but many similar "
    "person. You follow the instructions and format precisely and you try to change as "
    "little as possible, keep the original text intact as much as possible. Only generalize information and do not"
    " invent new information. "
    "Person names can be replaced with common pronoun like 'A person', the gender pronouns can be replaced with 'This person' or other "
    "personally identifiable entities can be replaced with more general counterparts. "
    "Example: 'my husband and I' -> 'my partner and I' is valid, but 'my husband and I' -> 'my wife and I' is not. "
    "Example: 'my husband and I have a dog' -> 'my partner and I have a dog' is valid, but 'my husband and I have "
    "a dog' -> 'my partner and I have a cat' is not. "
    "Example: 'my husband and I' -> 'I' is also valid as it only removes information.\n\n"
    "Note that the style, format and should not be changed."
    " You are only allowed to adapt small parts of the description text to make it anonymous."
    " Additionally, you can insert as little as possible tokens to ensure the final "
    "output text is fluent and natural while preserving anonymity. Removing or deleting content is not allowed, only decrease "
    "the specificity by generalizing. {format_instructions_2}\n\nThe biography is here: {input_text}"
)
SIMPLE_REWRITING_INSTRUCTION_COT = (
    "Let's now complete the second task. "
    "You are an expert anonymizer that carefully choose some of the personally identifiable entities (including words, dates, and numerals) of the given biography text "
    "that can be used to connect the person being talked about"
    " and then generalize them to make the biography text anonymous, namely the biography text can be suitable"
    " to describe not only a specific one person but many similar "
    "person. You follow the instructions and format precisely and you try to change as "
    "little as possible, keep the original text intact as much as possible. Only generalize information and do not"
    " invent new information. "
    "Person names can be replaced with common pronoun like 'A person', the gender pronouns can be replaced with 'This person' or other "
    "personally identifiable entities can be replaced with more general counterparts. "
    "Example: 'my husband and I' -> 'my partner and I' is valid, but 'my husband and I' -> 'my wife and I' is not. "
    "Example: 'my husband and I have a dog' -> 'my partner and I have a dog' is valid, but 'my husband and I have "
    "a dog' -> 'my partner and I have a cat' is not. "
    "Example: 'my husband and I' -> 'I' is also valid as it only removes information.\n\n"
    "Note that the style, format and should not be changed."
    " You are only allowed to adapt small parts of the description text to make it anonymous."
    " Additionally, you can insert as little as possible tokens to ensure the final "
    "output text is fluent and natural while preserving anonymity. Removing or deleting content is not allowed, only decrease "
    "the specificity by generalizing. {format_instructions_2}"
)
PRIVACY_REFLECTION_INSTRUCTION_1 = (
    "You are very knowledgeable about celebrities and can identify them from the given anonymized biography."
    " When asked to identify individuals, disregard any missing information and context, like placeholder"
    " '<PERSON>' or 'ORGANIZATION', respond only with the names of {p_threshold} celebrity candidates most "
    "likely being talked by the provided anonymized biography text and sort the names from highest to lowest"
    " probability. {format_instructions_1}\n\nThe anonymized biography text is here:\n{curr_rewriting}"
)
PRIVACY_REFLECTION_INSTRUCTION_2 = (
    "The person described by the text is {people}. If the name is within your output name list, respond with \'Yes\' "
    "and you need to detect and then respond me with the sensitive entities (including words, dates, and numerals)"
    " in the biography that you just used to infer the person's identity and should be generalized to decrease"
    " the confidence score of associating the person with the biography text. "
    "Otherwise, just give me the answer \'No\'. {format_instructions_2}"
)
UTILITY_REFLECTION_INSTRUCTION_1 = (
    "You are an expert at classifying people's occupation according to their anonymized biography. "
    "Given the anonymized biography of"
    " a person and its ground-truth occupation label, give me your confidence score of classifying the biography as"
    " the ground truth occupation label "
    "on a continuous scale ranging from 0 to 100 that starts with 0 corresponding to 'completely "
    "no confidence', goes through 1 - 50 corresponding to 'some details in the text matching the classification', "
    "then 51 - 99 corresponding to 'most details in the text matching the classification', up to 100 corresponding "
    "to 'the text completely matching the classification'. "
    # "\nThe optional occupation set is here:\n"
    # "Chef, Classical Music Artist, Table Tennis Player, Entomologist, Lacrosse Player, Astronaut, Medician,"
    # " Fashion Designer, Horse Trainer, Ambassador, Photographer, Engineer, Formula One Racer, Comedian, Martial Artist,"
    # " Chess Player, Painter, Soccer Player, Tennis Player, Architect, Cyclist, Basketball Player, Congressman, "
    # "Baseball Player."
    "\n{format_instructions}\nThe anonymized biography is here:\n{curr_rewriting}\nThe occupation label is {label}"
)
REINFORCEMENT_INSTRUCTION = (
    "Let's play a game to maximize accumulated rewards by editing biography texts. "
    "Here’s how it works: You'll be provided with a paragraph of biography text alongside its editing history. "
    "Each edit is associated with a privacy score, indicating the level of personal privacy maintained, and a utility "
    "score, reflecting its usefulness for a specific task.\n\n"
    "Your task is to edit the latest entry in the editing history. "
    "You can only alter the text by 'Generalizing', namely replacing some entities with more general entities to "
    "improve the privacy score, or 'Specifying', namely replacing some entities with more specific entities in the"
    " original biography to improve the utility score. \n"
    "Here are the rewarding rules:\n"
    "- If the privacy score is {p_threshold} or less, the reward is equivalent to the privacy score.\n"
    "- If the privacy score exceeds {p_threshold}, the reward is equivalent to the utility score.\n"
    "The editing goal is to get a higher reward than before while keeping changes to the "
    "text minimal, ensuring the original context and structure are preserved as much as possible. "
    "You are also permitted to make minor adjustments to the text to maintain fluency and naturalness.\n"
    "For example:\n"
    "- Generalize: 'my husband and I' can be changed to 'my partner and I'. Incorrect generalizations like changing "
    "'my husband and I' to 'my wife and I' are not allowed.\n"
    "- Specify: 'He is an athlete' can be changed to 'he is an tennis player' if 'tennis player' is mentioned in the"
    "original biography.\n\n"
    "Your ultimate goal is to maximize the total accumulated reward through strategic edits."
    " Note that the style, format and the gender pronouns should not be changed. "
    "\n{format_instructions}\n\nThe original biography is {input_text}\n\n{prev_rewriting}"
)
PRIVACY_EVALUATION_CONFIDENCE_INSTRUCTION = ("You are very knowledgeable about celebrities. When asked to identify "
                                             "individuals, given a paragraph of anonymized text and the name of "
                                             "a possible celebrity, disregard any missing or confused information and "
                                             "context, respond with me your confidence score of"
                                             " associating the person with the anonymized text "
                                             "on a continuous scale ranging from 0 to 100 that starts with 0 "
                                             "corresponding to 'completely irrelevant', goes through 1 - 50"
                                             " corresponding to 'some details matching', then 51 - 99 corresponding "
                                             "to 'most details matching', up to 100 corresponding to 'completely "
                                             "matching'. And then respond the reason why you give this score."
                                             " {format_instructions}\n\nThe anonymized text is here:"
                                             "\n{curr_rewriting}\nThe possible celebrity is {people}")
PRIVACY_EVALUATION_SELECTION_INSTRUCTION_1 = ("You are very knowledgeable about celebrities. "
                                              "Given a paragraph of anonymized celebrity biography and the name of the"
                                              "person described by the biography, generate a list of 9 celebrities that"
                                              "are so similar to the given celebrity that can also be described or"
                                              " partialy described by the given anonymized celebrity biography."
                                              " {format_instructions}\n\nThe anonymized text is here:\n{curr_rewriting}"
                                              "\nThe described celebrity is {people}")
PRIVACY_EVALUATION_SELECTION_INSTRUCTION_2 = ("You are very knowledgeable about celebrities. When asked to identify "
                                              "individuals, given a paragraph of anonymized text and a list of "
                                              "possible celebrity candidate, disregard any missing or confused "
                                              "information and context, choose the most possible celebrity from "
                                              "the candidate list. {format_instructions}\n\nThe anonymized text "
                                              "is here:\n{curr_rewriting}\nThe candidate list is here:"
                                              "\n{candidate_list}")
